/*CARA KONEKSI MYSQL via TERMINAL*/
cd xampp\mysql\bin;
> mysql -u root -p;

/*CARA MENANAMPILKAN DATA BASE*/
SHOW DATABASES;

/* CARA MEMBUAT DATABASE*/
CREATE DATABASE  `11RPL_DB`;


/* CARA MEMBUAT TABLE*/
CREATE TABLE  `SISWA`; (
id_siswa INT(11) PRIMARY KEY AUTOINCREMENT,
nis CHAR(10),
nama_lengkap VARCHAR(255),
jk CHAR(1),
tmp_lahir VARCHAR(255),
tgl_lahir DATE,
alamat TEXT,
no_hp CHAR(15),
tanggal_entry DATETIME
);


/*CARA MENAMPILKAN TABLE*/
SHOW TABLES;

/*CARA MENAMPILKAN SPESIFIKASI TABLE*/
DESCRIBE `siswa`;

/*CARA MENAMPILKAN RECORD KE TABLE*/
INSERT INTO `siswa`;
id_siswa = NULL,
nis = '11801050',
nama_lengkap ='IRFAN MUAMAR ZETA',
jk = 'L',
tmp_lahir = 'SUBANG ',
tgl_lahir ='2003-03-17',
alamat ='DUSUN GONDANGSARI RT 01 RW 03 DESA TAMBAKDAHAN KEC TAMBAKDAHAN KAB SUBANG PROV JAWA BARAT NEGARA INDONESIA',
no_hp ='089653740684',
tanggal_entry = NOW();

/*CARA MENAMPILKAN SDELURUH DATA TABLE*/
SELECT * FROM `siswa`;


/*CARA MENAMPILKAN DATA DENGAN KONDISI TERTENTU*/
SELECT * FROM `siswa` WHERE jk = 'P';


/*CARA MENAMPILKAN BEBERAPA RECORD/BATAS PADA TABLE*/
SELECT * FROM `siswa` LIMIT 3,5;

/*CARA MENAMPILKAN/MENGURUTKAN RECORD BERDASARKAN FIELD TERTENTU*/
SELECT * FROM `siswa` ORDERED BY tgl_lahir DESC;


/*CARA MENAMPILKAN FIELD MENGGUNAKAN FUNCTION*/
SELECT UPPER(alamat) FROM `siswa`;


/*CARA MENAMPILKAN BEBERAPA FIELD DENGAN KONDISI TERTENTU */
SELECT nama_lengkap, tmp_lahir,tgl_lahir, ='2003-01-12' WHERE id_siswa ='1';

/* CARA MENGHAPUS DATA RECORD*/
DELETE FROM `siswa` WHERE id_siswa ='1';




